textstats/stats/urls.py
#  MIT License
#
#  Copyright (c) 2020. Morning Project Samurai Inc. (MPS)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

from django.urls import path
from . import views

urlpatterns = [
    path('list/', views.ListView.as_view(), name='list'),
    path('detail/<int:id>/', views.DetailView.as_view(), name='detail'),
    path('upload/', views.UploadView.as_view(), name='upload'),
]

textstats/textstats/urls.py
#  MIT License
#
#  Copyright (c) 2020. Morning Project Samurai Inc. (MPS)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

from django.contrib import admin
from django.urls import path, include

app_name = 'stats'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stats/', include(('stats.urls', 'stats'), namespace='stats')),
]

textstats/stats/models.py
#  MIT License
#
#  Copyright (c) 2020. Morning Project Samurai Inc. (MPS)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

from django.shortcuts import reverse
from django.db import models


# Create your models here.
class Text(models.Model):
    body = models.TextField()
    nouns = models.TextField(null=True, blank=True)

    STATUS_CHOICES = (('UPLOADED', 'アップロード完了'),
                      ('ANALYZING', '分析中'),
                      ('COMPLETED', '分析完了'),)
    status = models.CharField(max_length=24, choices=STATUS_CHOICES, default='UPLOADED')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )

    def get_absolute_url(self):
        return reverse('stats:detail', args=(self.id, ))

    def __str__(self):
        return self.body[:20]

textstats/stats/forms.py
#  MIT License
#
#  Copyright (c) 2020. Morning Project Samurai Inc. (MPS)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

from django import forms
from . import models


class UploadForm(forms.ModelForm):
    min_length = forms.IntegerField(min_value=1, initial=1)
    top_k = forms.IntegerField(min_value=1, initial=20)

    class Meta:
        model = models.Text
        fields = ('body', )

textstats/stats/views.py
#  MIT License
#
#  Copyright (c) 2020. Morning Project Samurai Inc. (MPS)
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

import json
from django.shortcuts import render, redirect
from django import views
from django.core.paginator import Paginator
from . import forms
from . import models
from . import tasks


# Create your views here.
class ListView(views.View):
    def get(self, request):
        paginator = Paginator(models.Text.objects.all(), 10)
        page_obj = paginator.get_page(request.GET.get('p', 1))
        return render(request, 'stats/list.html', {'texts': page_obj})


class DetailView(views.View):
    def get(self, request, id):
        text = models.Text.objects.get(id=id)
        if text.nouns:
            nouns = json.loads(text.nouns)
            max_count = max(nouns.values())
            graph = {k: {'count': v, 'bar': '#' * (int(v * 50 / max_count) + 1)} for k, v in nouns.items()}
        else:
            graph = {}
        return render(request, 'stats/detail.html', {'text': text, 'graph': graph})


class UploadView(views.View):
    def get(self, request):
        form = forms.UploadForm()
        return render(request, 'stats/upload.html', {'form': form})

    def post(self, request):
        form = forms.UploadForm(request.POST)
        if not form.is_valid():
            return render(request, 'stats/upload.html', {'form': form})
        form.save()
        tasks.count_nouns.delay(form.instance.id, form.instance.body,
                                form.cleaned_data['min_length'], form.cleaned_data['top_k'])
        return redirect('stats:list')

textstats/stats/templates/stats/base.html
<html>
<head>
    <title>TextStats</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
        h1 {
            margin-top: 0.5em;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'stats:list' %}">TextStats</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'stats:list' %}">一覧</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'stats:upload' %}">アップロード</a>
            </li>
        </ul>
    </div>
</nav>

<div

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

textstats/stats/templates/stats/detail.html
{% extends 'stats/base.html' %}

{% block content %}
    <h1>文書</h1>
    {{ text.body|truncatechars:200 }}

    <h1>分析結果</h1>
    <table class="table">
        <thead>
        <tr>
            <td>ランク</td>
            <td>名詞 (個数)</td>
            <td>グラフ</td>
        </tr>
        </thead>
        <tbody>
        {% for k, v in graph.items %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ k }} ({{ v.count }})</td>
                <td>{{ v.bar }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

textstats/stats/templates/stats/list.html
{% extends 'stats/base.html' %}

{% block content %}
    <h1>文書リスト</h1>
    <table class="table">
        <thead>
        <tr>
            <th>文書</th>
            <th>状態</th>
            <th>アップロード日時</th>
        </tr>
        </thead>
        <tbody>
        {% for t in texts %}
            <tr>
                <td><a href="{{ t.get_absolute_url }}">{{ t.body|truncatechars:20 }}</a></td>
                <td>{{ t.get_status_display }}</td>
                <td>{{ t.created }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if texts.has_previous %}
        <a class="btn btn-primary" href="{% url 'stats:list' %}?p={{ texts.previous_page_number }}">前へ</a>
    {% else %}
        <button class="btn btn-primary disabled">前へ</button>
    {% endif %}
    {% if texts.has_next %}
        <a class="btn btn-primary" href="{% url 'stats:list' %}?p={{ texts.next_page_number }}">次へ</a>
    {% else %}
        <button class="btn btn-primary disabled">次へ</button>
    {% endif %}
     ({{ texts.number }} / {{ texts.paginator.num_pages  }})
{% endblock %}

textstats/stats/templates/stats/upload.html
{% extends 'stats/base.html' %}

{% block content %}
    <h1>文書アップロード</h1>
    <form method="post">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
        </table>
        <input type="submit" class="btn btn-primary" value="アップロード">
    </form>
{% endblock %}